version: '2'
services:
    flowable-all-in-one:
        image: flowable/all-in-one
        container_name: flowable-all-in-one
        depends_on:
            - flowable-db
        environment:
            - datasource.driver=org.postgresql.Driver
            - datasource.url=jdbc:postgresql://flowable-db:5432/flowable
            - datasource.username=flowable
            - datasource.password=flowable
        ports:
            - 8080:8080
    flowable-db:
        extends:
            file: postgres.yml
            service: flowable-postgres

